### ISSUE TITLE
Improve lint option reporting

### ISSUE THREAD

**Issue by necolas** [csscomb/csscomb.js#245]
Would be good for the `--lint` option to output line:column information about where there are problems, and what the issue is. At the moment it only tells you which files have issues but leaves you to hunt them down.
##

**Comment by ismay** [comment]
Since this issue is already pretty old, and a lot of people are looking forward to the feature, I was wondering if there's a specific timeframe for the 3.2 release (and the improved linting)? Right now there's no date specified.

It's been a while, and necolas has already closed his issue regarding csscombs linting because of the inactivity. Any specific issues that are holding this back, or is it a lack of available time? I'm still hoping that we can move this forward! It would be a shame for csscomb to be abandoned.

**Comment by MoOx** [comment]
If you are looking for some linting, you should take a look to stylelint which is (thanks to @davidclark) taking a really good shape ! https://github.com/stylelint/stylelint/tree/master/src/rules

**Comment by ismay** [comment]
@MoOx Ah, that looks like a very good alternative, thanks!

**Comment by MoOx** [comment]
No release yet, but one will be here really soon !

**Comment by tonyganch** [comment]
It's lack of time now only.
The issue did depend on some work with parser which i've (hopefully) finished this week.
Now the order of issues to close is following:
- [x] Add lint methods to api (like `lintFile` and `lintString`)
- [ ] Add lint methods to current options so they return a list of found errors
- [ ] Format error messages to display them nicely in terminal

It'll take some more time but i'm working on it.
As for version number, i think it'll actually be 4.0 (skipping 3.2) because of some backwards incompatibilities. ETA is mid of summer.

**Comment by ismay** [comment]
@tonyganch Cool, that's good to know. Thanks for the quick reply!
