### ISSUE TITLE
image-path issue

### ISSUE THREAD

**Issue by Bitaru** [csscomb/csscomb.js#260]
Hi guys!
I caught a bug - Gonzales threw error for Rails assets pipeline function image-path().
In SASS it looks like "background-image: url(image-path("icons-sprite.png"))"

**Comment by QuentinFchx** [comment]
@tonyganch are we sure nothing can be done here ?
The scope is very limited (only `background`, `background-url` properties) for a huge added value to the plugin.
I can try to provide a PR, but first I need to make sure that it's relevant enough to be included in the project.

I think something similar is already done for urls.
Given the current code, the issue here is the presence of a dash `-` in the keywords but we can use a different array for punctuation.

The work-around I found for now is to :
- put all my assets-related stuff in a separate file
- import this assets file into the main one
- add an ignore rule for this assets-file to csscomb
BUT, it becomes hard to maintain.
