### ISSUE TITLE
Exclude properties from sorting

### ISSUE THREAD

**Issue by urecio** [csscomb/csscomb.js#361]
Is it possible to exclude specific properties from being sorted?
I would like to have some of them free from being sorted, like @import in scss

**Comment by alinchican** [comment]
Check [this](https://github.com/csscomb/csscomb.js/blob/master/doc/options.md#sort-order-vs-preprocessors) out.

You can find all configuration options [here](https://github.com/csscomb/csscomb.js/blob/master/doc/options.md).

**Comment by tonyganch** [comment]
@urecio, if you use default config and your imports are being sorted, this is a bug.
If you want to specify the order of includes or imports, you can write custom config with `sort-order` option specified.
If the issue is still relevant and you need any help, please give me a sample code that makes you unhappy and share your config.
