### ISSUE TITLE
Issue With 'always-semicolon'?

### ISSUE THREAD

**Issue by d4rkr00t** [csscomb/csscomb.js#447]
I'm seeing an issue with the `always-semicolon` option in the config.

csscomb 3.1.8, OSX 10.10

My config contains `"always-semicolon": true`, but it doesn't always add the missing semicolon on individual CSS declarations. 

Here are some things I've noticed:
- If the last declaration is the only one missing it's semicolon, running css-comb-atom adds it. If any other declarations are missing their semicolon they don't get added.
- If all declarations are missing their semicolons then no sorting happens and only the last semicolon get added.

In trying to get my config how I want it I've been playing around with this block of CSS:
```css
.test {
    position: absolute
    display: block
    padding: 0 10px 0 0
    margin: auto
    color: red
    border-color: green
}
```

Here is a link to my `.csscomb.json` file: https://www.dropbox.com/s/c4roltd95x4cb1b/csscomb.json?dl=0

**Comment by sodatea** [comment]
That's not valid css syntax, and csscomb is only expected to fix code style issues for a valid css block.
What the `always-semicolon` option actually do is "to add a semicolon after the last value/mixin".

As for the second point, I think it is a bug in the parser. It should raise an 'invalid syntax' error for missing semicolons. Will check that later.

**Comment by wylie** [comment]
Just some backstory… I am setting up a `.csscomb.json` file for use on a team. I want it to format the CSS so when one team member opens a stylesheet that another team member worked on they won't need to decipher any crazy, and perhaps not valid, CSS writing style. Making all stylesheets neat and uniform for easier editing. [CSSComb](https://github.com/csscomb/csscomb.js) works great for this, and [css-comb-atom](https://github.com/d4rkr00t/css-comb-atom) is the best plugin I've found for Atom. 

I guess I didn't understand the [documentation for `always-semicolon`](https://github.com/csscomb/csscomb.js/blob/master/doc/options.md#always-semicolon). The line *"Whether to add a semicolon after the last value/mixin"* is what I should have focused on instead of this example.

```css
/* before */
a { color: red }

/* after */
a { color: red; }
```

The example, though following the descriptive text, misled me into thinking it would add semicolons to all declarations within a block. Also, I'm not 100% sure what the benefit to only adding it to the last declaration is.

I appreciate your looking into this and creating the bug on the CSS parser Gonzales PE. Thanks!

**Comment by sodatea** [comment]
Just modified the example in the documentation. Now it‘s less likely to be misunderstood :)
