### ISSUE TITLE
Only blank space on crowded elements

### ISSUE THREAD

**Issue by geirmarius** [csscomb/csscomb.js#448]
Would be nice to only apply the blank line where there is too many CSS rules.
This looks kinda ridicules: 

```
dropdown-list d-li {
  padding: calc(var(--spacing-element) * 1.5) var(--spacing-element);

  display: flex;

  background: var(--el-color);

  justify-content: space-between;
}
```
##

**Comment by joemaller** [comment]
@geirmarius Can you provide an example of what the rule would look like with your proposed setting?

**Comment by tonyganch** [comment]
Hey @geirmarius! That's been originally done as a plugin a couple of years ago, so you can configure min number of declarations in a block for it to be separated by a new line:
https://github.com/tonyganch/csscomb-group-size
Though I haven't touched it since then because there was no interest for such option.
If you find it helpful enough, I can refresh it a bit so it works with the latest csscomb.

**Comment by handmadedigital** [comment]
Any news on this? I agree it would look nicer if space only came when there are two or more attributes.

This: 
`dropdown-list d-li {
  background: var(--el-color);
  background-size: center;

  padding: calc(var(--spacing-element) * 1.5) var(--spacing-element);
  display: flex;
  justify-content: space-between;
}`

vs: 
`dropdown-list d-li {
  background: var(--el-color);
  background-size: center;

  padding: calc(var(--spacing-element) * 1.5) var(--spacing-element);

  display: flex;

  justify-content: space-between;
}`

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
