### ISSUE TITLE
CSScomb error: (node:12779)

### ISSUE THREAD

**Issue by hirschferkel** [csscomb/csscomb.js#598]
CSScomb error:
(node:12779) UnhandledPromiseRejectionWarning: Cannot set property 'atrulers_end' of undefined
CSScomb Core version: 4.2.0
(node:12779) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12779) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tonyganch** [comment]
Hey @hirschferkel, could you please provide more info? For example, failing css code and node version.

**Comment by hirschferkel** [comment]
I use another plugin, now, as it did not work at all. As you can see in the code this a console message where the plugin cold not be set up to work at all.

**Comment by tonyganch** [comment]
`Cannot set property 'atrulers_end' of undefined`

This error is hard to investigate if there is no css code that we can point to: "Oh, this specific line is broken, maybe because css is invalid, or maybe because this option is being applied".
I will close this issue for now, if you'll manage to identify the broken piece of code, please re-open this issue, i'll be glad to look into it.
